baseURL = 'https://DeconstructionMechanics.github.io/'
languageCode = 'en-us'
title = 'DM'
content = 'DeconstructionMechanics : 解構力学者(かいこう りきがくしゃ, kaikou-rikigakusha) : 解构力学家(jiegoulixuejia)'
theme = 'ananke'

copyright = 'copyright blablabla'

[param]
  [homeInfoParam]
    Title = "DeconstructionMechanics's Page"
    Content = 'DeconstructionMechanics : 解構力学者(かいこう りきがくしゃ, kaikou-rikigakusha) : 解构力学家(jiegoulixuejia)'
  [socialIcons]
    # - name: "email"
    #   url: ""
    name = "github"
      url = "https://github.com/DeconstructionMechanics"

[menu]
[[menu.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 10
[[menu.main]]
    name = 'Research'
    pageRef = '/research'
    weight = 20
[[menu.main]]
    name = 'Github'
    pageRef = 'https://github.com/DeconstructionMechanics/DeconstructionMechanics.github.io'
    weight = 30
    